version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    restart: always
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
