version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Use the Dockerfile you created
    ports:
      - "3000:3000"  # Adjust the port as needed

  owasp-dependency-check:
    image: owasp/dependency-check:latest
    volumes:
      - .:/src
    command: ["--scan", "/src"]
