version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: development

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
