version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Adjust the port as needed

  owasp-dependency-check:
    image: owasp/dependency-check
    volumes:
      - .:/
    command: ["--scan", "/"]
